# Site settings
title: CHRӨMA
email: kate@chroma.space
description: > # this means to ignore newlines until "baseurl:"
  chroma.space is a creative studio investigating the warp & the rift to feel out alternatives on the horizon. 
  ecosphere ∩ cybersphere

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
permalink: none
twitter_username: chroma_space
chroma: <span class="chroma">CHRΘMA</span>
github_username:  kategenevieve
# Build settings
markdown: kramdown
prose:
  siteurl: http://chroma.space
  media: 'assets/images'
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: title
      - name : slug
        field:
          element: text
          label: slug
      - name: "description"
        field:
          element: text
          help: appears on post summary on index page
          label: description
      - name: jpg
        field:
          element: text
          label: jpg image
      - name: png
        field:
            element: text
            label: png image
      - name: video
        field:
          element: text
          label: video ( exclude file extension )
      - name: poster
        field:
          element: text
          label: video poster
      - name : panorama
        field:
          element: text
          label: "panorama image"
      - name: panorama-poster
        field:
          element: text
          label: "panorama poster image"
      - name: panorama-longitude-speed
        field:
          element: number
          value: 0.01
          label: "panorama rotation speed"
      - name: panorama-user-control
        field:
          element: checkbox
          value: false
          label: "can user control panorama"
      - name: invert-nav
        field:
          element: checkbox
          value: false
          label: "invert menu colours"
      - name: splash-description
        field:
          element: text
          label: "splash description"
      - name: index-image
        field:
          element: text
          label: "index image"
      - name: date
        field:
          element: text
          label: "Date {yyyy-mm-dd}"
          value: "2015-01-01"
      - name: categories
        field:
          element: text
          label: categories
          value: "blog"
    _posts/projects:
      - name: layout
        field:
          element: hidden
          value: post
      - name : title
        field:
          element: text
          label: title
      - name : slug
        field:
          element: text
          label: slug
      - name: description
        field:
          element: text
          label: description
      - name : thumbnail
        field:
          element: text
          label: "thumbnail image ( 512x512 )"
      - name: jpg
        field:
          element: text
          label: jpg image
      - name: png
        field:
            element: text
            label: png image
      - name: video
        field:
          element: text
          label: video ( exclude file extension )
      - name: video-pause
        field:
          element: checkbox
          label: video pausable
      - name: play-once
        field:
          element: checkbox
          label: play video once
      - name: video_mute
        field:
          element: checkbox
          label: video mutable
      - name: panorama
        field:
          element: text
          label: "panorama image"
      - name: panorama-poster
        field:
          element: text
          label: "panorama poster image"
      - name: panorama-longitude-speed
        field:
          element: number
          value: 0.01
          label: "panorama rotation speed"
      - name: panorama-user-control
        field:
          element: checkbox
          value: false
          label: "can user control panorama"
      - name: invert-nav
        field:
          element: checkbox
          value: false
          label: "invert menu colours"
      - name: splash-description
        field:
          element: text
          label: "splash description"
      - name: index-image
        field:
          element: text
          label: "index image"
      - name: date
        field:
          element: text
          label: "Date {yyyy-mm-dd}"
          value: "2015-01-01"
      - name: categories
        field:
          element: hidden
          label: categories
          value: "projects"
      - name: banner-align
        field:
          element: select
          label: "Banner Alignment"
          options:
            - name: "Top"
              value: "top"
            - name: "Top Left"
              value: "top-left"
            - name: "Top Right"
              value: "top-right"
            - name: "Bottom"
              value: "bottom"
            - name: "Bottom Left"
              value: "bottom-left"
            - name: "Bottom Right"
              value: "bottom-right"
