# Site settings
title: CHRÓ¨MA
email: paul@chroma.space
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
permalink: none
twitter_username: chroma_
github_username:  paul_hayes

# Build settings
markdown: kramdown
prose:
  media: 'assets/images'
  metadata:
    _posts:
      - name : title
        field:
          element: text
      - name : slug
        field:
          element: text
      - name: description
        field:
          element: text
      - name : panorama
        field:
          element: text
      - name: panorama-poster
        field:
          element: text
      - name: panorama-longitude-speed
        field:
          element: number
      - name: panorama-user-control
        field:
          element: checkbox
          value: false
      - name: invert-nav
        field:
          element: checkbox
          value: false
      - name: splash-description
        field:
          element: text
      - name: index-image
        field:
          element: text
